
training_pipeline_config:
  pipeline_name: model #  Pipeline name
  artifact_dir: artifact # All artifacts are stored here from each artifcat 

data_ingestion_config:
  download_url: wenruliu/adult-income-dataset
  raw_dir: raw
  tgz_dir : tgz_data
  ingested_dir : ingested
  train_dir: train
  test_dir: test
